name: Benchmark

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: moonrepo/setup-rust@v1
        with:
          cache-target: release
          bins: cargo-codspeed

      - name: Build
        run: cargo codspeed build

      - name: Bench
        uses: CodSpeedHQ/action@v2
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}
