name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: moonrepo/setup-rust@v1
        with:
          profile: default

      - name: Check
        run: cargo check --locked

      - name: Format
        run: cargo fmt --check

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test
